name: base
channels:
  - conda-forge
  - anaconda
dependencies:
  - python<=3.9
  - cython=0.29.32
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib=3.6.2
  - yfinance
  - lightgbm
  - scipy=1.10.0ju
  - statsmodels=0.13.5
  - pmdarima=2.0.1
  - prophet=1.1.1
  - tensorflow>=2.8
  - tensorflow-probability=0.14.0
  - keras-preprocessing
